{% set name = "pillow-avif-plugin" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pillow-avif-plugin-{{ version }}.tar.gz
  sha256: 855cf50d03f6fc16e1fd5e364b3cea0b79f4bf90d39ff2123969735d851e08ba

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - libavif
    - pip
    - python
    - setuptools
  run:
    - pillow
    - python

test:
  imports:
    - pillow_avif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fdintino/pillow-avif-plugin/
  summary: A pillow plugin that adds avif support via libavif
  dev_url: https://github.com/fdintino/pillow-avif-plugin/
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
