{% set name = "pillow-avif-plugin" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 460d3dcade7f22f3c30873f3425a863894595169f61a70a6c150c2a2daaa96ec

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - libavif
    - pip
    - python
    - setuptools
  run:
    - pillow
    - python

test:
  imports:
    - pillow_avif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fdintino/pillow-avif-plugin/
  summary: A pillow plugin that adds avif support via libavif
  dev_url: https://github.com/fdintino/pillow-avif-plugin/
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
